docs/00-preamble/02-what-is-not-covered.adoc, docs/01-basics/01-basics-duration-terms.adoc, docs/01-basics/LZ-1-04.adoc, docs/09-references/00-references.adoc
Hallo zusammen,
ich habe wenige kleine Tippfehler (Trennzeichen) gefunden, die mir beim ersten Durchgehen aufgefallen sind.
Weiter habe ich die Literaturangaben am Ende versucht vollständig zu machen. [Bass 2003] ist mir nicht ganz klar. Ist hier die 2. Auflage gemeint?
"Inhaltliche Redundanzen" schaue ich mir in den nächsten Tagen noch an, wenn ich das Grundgerüst des Referenzfoliensatzes aufsetze.
Viele Grüße
Jörg
=> Fixed some typos and revised references at the end

build.gradle
=> Apply latest changes of pdf theme

docs/04-quality/99-quality-references.adoc
Replace outdated reference Bass+2003 with Bass+2012
Fixes #123
=> Fix missing references

docs/01-basics/LZ-1-01.adoc, docs/03-documentation/LZ-3-03.adoc
=> 152 fix spelling of cross cutting

docs/03-documentation/LZ-3-03.adoc
this fixes #160, spelling mistake in LG 3-3 (imho in EN version only)
=> fixed #160, corrected names of UML diagram types in LG 3-3

docs/02-design/LZ-2-05.adoc
See https://github.com/isaqb-org/curriculum-foundation/issues/204
=> Delete part that Microservices and SCS are the same thing

build.gradle, docs/index.adoc
=> Remove Bilingual Build

docs/02-design/01-design-duration-terms.adoc, docs/02-design/LZ-2-01.adoc
=> Unify spelling in German

docs/02-design/LZ-2-05.adoc
=> fixed #271 for LG 2-5 (explain abbreviations)

docs/01-basics/LZ-1-04.adoc, docs/01-basics/LZ-1-10.adoc, docs/02-design/LZ-2-06.adoc, docs/02-design/LZ-2-09.adoc
=> Clarify "Architekturentwurf".

docs/04-quality/LZ-4-3.adoc
(after the mess with the for…gotten branch)
=> LG 4-3, this should resolve #249 finally 

docs/02-design/LZ-2-05.adoc, docs/09-references/00-references.adoc
add the term plus one reference
=> #250, LG 2-5 add the term clean-architecture

docs/04-quality/LZ-4-4.adoc
=> LZ-4-4 Minor translation change

docs/02-design/LZ-2-06.adoc
this is the PR for issue #247 . Could one of the reviewers please merge this PR.
=> #247 reduce prio of kiss and yagni to R3

docs/01-basics/99-basics-references.adoc, docs/02-design/99-design-references.adoc, docs/03-documentation/99-documentation-references.adoc, docs/04-quality/99-quality-references.adoc, docs/09-references/00-references.adoc
it would be great if somebody else except Alexander Lorz and myself could check this one... (as we are the authors of the book)
to be more specific: decide if the book is a good-enough source to be included into our reference-list.
=> #295 add book / reference Lorz-Starke 2021

docs/02-design/LZ-2-03.adoc
after lengthy discussion on #291, hopefully a viable compromise with the plural form.
=> LG 2-3, #291 gendering -> pluralized sentence

docs/09-references/00-references.adoc
as explained in #309, there is no perceived value in adding ISBN numbers, so I removed the few we had.
=> #309 - removed inconsistent ISBN numbers,

docs/03-documentation/LZ-3-02.adoc
original comment: Dear reviewers, please DO NOT MERGE, but only comment... we might need to consolidate your comments or suggestions.
update Nov 20th: 2 reviewers gave "fine-by-me", so I merge
=> #313 lg 3 2 wording and relevance level issues

docs/00-preamble/01-what-to-expect.adoc, docs/00-preamble/05-exam-relevance-levels.adoc, docs/01-basics/LZ-1-04.adoc, docs/01-basics/LZ-1-07.adoc, docs/01-basics/LZ-1-08.adoc, docs/01-basics/LZ-1-10.adoc, docs/02-design/00-design.adoc, docs/02-design/LZ-2-02.adoc, docs/02-design/LZ-2-06.adoc, docs/02-design/LZ-2-07.adoc, docs/02-design/LZ-2-10.adoc
the first dozen or so typos (mostly found by LanguageTool)
=> #332 fix typos

docs/02-design/LZ-2-04.adoc, docs/02-design/LZ-2-05.adoc, docs/02-design/LZ-2-06.adoc, docs/09-references/00-references.adoc
=> #332 more trivial typos

.github/workflows/build_releasecandidate.yml, CHANGELOG.md, docs/index_rc.adoc
- Add separate `index_rc.adoc` to create an index page for Release Candidates
- Update RC workflow file to replace the regular `index.adoc` with `index_rc.adoc`
- Fix commits since in Changelog.md
=> Add RC info page

build.gradle, docs/config/setup.adoc
- Replace Leanpub URL with `public.isaqb.org`
- Set default URL if none is set in `build.gradle`
- Set language specific URL in `build.gradle`
=> Migrate Links to GitHub Glossary

docs/01-basics/LZ-1-08.adoc
Change DE version to make it consistent with EN
Old: Explizite von impliziten Aussagen unterscheiden
New: Explizite Aussagen von impliziten Annahmen unterscheiden
Fixes #378
=> Fix translation LG 1-8

docs/01-basics/LZ-1-08.adoc
=> Remove nonsense

docs/02-requirements/LZ-02-04.adoc
=> Redo wording on requirements / methods of analysis

docs/01-basics/01-basics-duration-terms.adoc
First proposal for a purpose statement for Chapter 1
=> Add purpose statement to Chapter 1 LGs, refs #411

docs/03-design/01-design-duration-terms.adoc, docs/03-design/LZ-03-09.adoc
=> fix #456, crosscutting / querschnittlich

docs/00-preamble/03-prerequisites.adoc, docs/01-basics/LZ-01-02.adoc, docs/01-basics/LZ-01-03.adoc, docs/01-basics/LZ-01-04.adoc, docs/01-basics/LZ-01-05.adoc, docs/02-requirements/LZ-02-01.adoc, docs/02-requirements/LZ-02-02.adoc, docs/02-requirements/LZ-02-03.adoc, docs/02-requirements/LZ-02-04.adoc, docs/02-requirements/LZ-02-05.adoc, docs/03-design/LZ-03-03.adoc, docs/03-design/LZ-03-04.adoc, docs/03-design/LZ-03-08.adoc, docs/03-design/LZ-03-09.adoc, docs/03-design/LZ-03-10.adoc, docs/03-design/LZ-03-11.adoc, docs/04-documentation/LZ-04-02.adoc, docs/04-documentation/LZ-04-04.adoc, docs/04-documentation/LZ-04-06.adoc, docs/04-documentation/LZ-04-08.adoc, docs/05-evaluation/LZ-05-01.adoc, docs/05-evaluation/LZ-05-02.adoc, docs/05-evaluation/LZ-05-03.adoc, docs/06-examples/LZ-06-01.adoc, docs/06-examples/LZ-06-02.adoc
Removed TODO and fixed some translations in headings and typos in text
=> #464 check and fix minor translation issues

docs/03-design/LZ-03-03.adoc, docs/09-references/00-references.adoc
add references for view-based architecture, both in LG and reference-section.
Fixing #422
=> #422 sources for arch views

docs/04-documentation/LZ-04-04.adoc, docs/09-references/00-references.adoc
as this is a trivial renaming, I merge this PR without review, and take full responsibility.
=> #468-change-title-of-LG-04-04

docs/09-references/00-references.adoc
if one of you could please take a brief look... trivial change.
=> #434 updated references, added missing iSAQB glossary etc

docs/01-basics/00-basic-concepts.adoc, docs/01-basics/99-basics-references.adoc, docs/01-basics/LZ-01-06.adoc, docs/09-references/00-references.adoc
Also, include reference to Felleisen et al. and Sperber/Klaeren books on data modelling.  Hope that's OK.
Fixes #429.
=> LG on modelling.

docs/03-design/LZ-03-03.adoc, docs/03-design/LZ-03-05.adoc
Fixes #403, as discussed by FLWG on 2024-05-02.
=> Move iterative/incremental content.

docs/03-design/LZ-03-06.adoc
Fixes #415.
This is just a draft at this point: I didn't rewrite anything, just added what the issue says.
=> Add specifics on kinds of coupling.

docs/05-evaluation/LZ-05-02.adoc
- that definitely was NOT the content of the old LG 4-2
- for the sake of keeping track what went where this is important, even if we remove this information in the final release
=> Correct relation to old LGs for LG 05-02

docs/config/setup.adoc
will merge this myself without review
=> #485 - fix bug in typo (merged without PR)

docs/03-design/LZ-03-04.adoc
=> Reduce number of exam-relevant design principles

docs/01-basics/LZ-01-06.adoc
=> LG 1-06, unify relevance to R2, adressing #502

docs/09-references/00-references.adoc
just one more entry in our list of references.
=> #513: add Martin Kleppmann, Designing Data Intensive Applications

docs/01-basics/LZ-01-06.adoc
=> Add HtDP/SdP references specifically to sums/products LG.

docs/03-design/LZ-03-02.adoc, docs/03-design/LZ-03-04.adoc, docs/03-design/LZ-03-07.adoc, docs/03-design/LZ-03-10.adoc, docs/04-documentation/LZ-04-06.adoc, docs/04-documentation/LZ-04-07.adoc, docs/05-evaluation/LZ-05-02.adoc
I added a few cross-references
=> #267 add xrefs between learning goals.

docs/00-preamble/04-structure-timing-didactics.adoc
changes as @gernotstarke suggested
=> #492: timing proposals adjusted

docs/01-basics/LZ-01-03.adoc
Translate "Gesamtverantwortung der Projektleitung" as "overall project
responsibility of project management"
fix #523
=> LG-01-03: Fix translation inconsistency "Gesamtverantwortung"

docs/01-basics/LZ-01-03.adoc, docs/02-requirements/LZ-02-03.adoc
There is no issue because the fixes are so simple.
=> minor fixes

docs/02-requirements/LZ-02-04.adoc, docs/03-design/99-design-references.adoc, docs/03-design/LZ-03-02.adoc, docs/03-design/LZ-03-11.adoc, docs/09-references/00-references.adoc
=> Some references for LG-{1,2,3}

docs/01-basics/01-basics-duration-terms.adoc
- the underlying learning goal is long gone
=> Remove Types of IT Systems from Relevant Terms, refs #538

docs/02-requirements/LZ-02-01.adoc
=> Specify Exam Relevance for LG 02-01

docs/04-documentation/LZ-04-03.adoc, docs/09-references/00-references.adoc
=> #547, LG-04-03, added ERD and Peter Chen reference

docs/01-basics/LZ-01-03.adoc
=> #539, LG-01-03: slightly changed wording regarding to requirements

docs/02-requirements/LZ-02-03.adoc
according to #545 the quotes have been removed, AND
the introductory sentence has been reworded.
=> #545 LG-02-03, rephrased intro sentence. Removed quotes.

docs/00-preamble/04-structure-timing-didactics.adoc
=> add table footer so bottom line gets visually separated

docs/02-requirements/LG-02-03.adoc
=> LG 02-03: Fix relevance levels and redundancies

docs/01-basics/01-basics-duration-terms.adoc, docs/01-basics/LG-01-02.adoc, docs/01-basics/LG-01-03.adoc, docs/01-basics/LG-01-05.adoc
=> Chapter 1: Fix translation inconsistencies

docs/01-basics/LG-01-05.adoc
=> LG 01-05 Add system architects

docs/02-requirements/01-requirements-duration-terms.adoc
=> Chapter 2: Add missing terms, align translations

docs/01-basics/LG-01-06.adoc
=> Remove redundant references for "products and sums"

docs/02-requirements/LG-02-03.adoc
=> LG 02-03 fix broken IREB reference

docs/02-requirements/LG-02-02.adoc
=> LG 02-02 remove blockchain, align translation

docs/02-requirements/01-requirements-duration-terms.adoc, docs/02-requirements/LG-02-01.adoc, docs/02-requirements/LG-02-02.adoc, docs/02-requirements/LG-02-03.adoc, docs/02-requirements/LG-02-05.adoc
=> Chapter 2: Fix translation inconsistencies and minor issues

docs/03-design/01-design-duration-terms.adoc
=> Chapter 3 Align terms DE-EN

docs/02-requirements/LG-02-01.adoc
=> LG 02-01 Fix phrasing

docs/03-design/LG-03-03.adoc
=> Replace "model-driven architecture" with model-based design

docs/03-design/01-design-duration-terms.adoc, docs/03-design/LG-03-02.adoc, docs/03-design/LG-03-04.adoc, docs/03-design/LG-03-05.adoc, docs/03-design/LG-03-07.adoc, docs/03-design/LG-03-09.adoc, docs/03-design/LG-03-10.adoc
=> Chapter 3 Fix translations, wording, redundant relevance levels

docs/03-design/LG-03-04.adoc
=> LG 03-04: Modularization is all R1

docs/01-basics/00-basic-concepts.adoc, docs/02-requirements/00-requirements.adoc, docs/02-requirements/99-requirements-references.adoc, docs/02-requirements/LG-02-03.adoc, docs/02-requirements/LG-02-04.adoc, docs/03-design/00-design.adoc, docs/03-design/99-design-references.adoc, docs/03-design/LG-03-02.adoc, docs/03-design/LG-03-04.adoc, docs/03-design/LG-03-06.adoc, docs/03-design/LG-03-07.adoc, docs/03-design/LG-03-08.adoc, docs/03-design/LG-03-09.adoc, docs/03-design/LG-03-10.adoc, docs/03-design/LG-03-11.adoc, docs/03-design/LG-03-12.adoc, docs/04-documentation/00-documentation.adoc, docs/04-documentation/99-documentation-references.adoc, docs/04-documentation/LG-04-01.adoc, docs/04-documentation/LG-04-03.adoc, docs/04-documentation/LG-04-04.adoc, docs/04-documentation/LG-04-08.adoc, docs/04-documentation/LG-04-09.adoc, docs/05-evaluation/00-evaluation.adoc, docs/05-evaluation/99-evaluation-references.adoc, docs/05-evaluation/LG-05-01.adoc, docs/05-evaluation/LG-05-02.adoc, docs/06-examples/LG-06-01.adoc, docs/06-examples/LG-06-02.adoc, docs/09-references/00-references.adoc
added a few references with examples.
=> #576 add references for examples

docs/02-requirements/LG-02-01.adoc
@rhoadesre you requested this change :-), please check this PR
=> LG-02-01 improve wording, re-order table

docs/04-documentation/LG-04-09.adoc, docs/09-references/00-references.adoc
=> Issue #575 - Remove FMC

docs/03-design/LG-03-10.adoc
Changed German version to be consistent with the English version and remove conflicting semantic meanings. See Issue #546
=> Update LG-03-10.adoc Consistency between German and English and semantics

docs/04-documentation/01-documentation-duration-terms.adoc, docs/04-documentation/LG-04-01.adoc, docs/04-documentation/LG-04-02.adoc, docs/04-documentation/LG-04-03.adoc, docs/04-documentation/LG-04-09.adoc
=> Chapter 4 Fix translation inconsistencies and minor issues

docs/05-evaluation/01-evaluation-duration-terms.adoc, docs/05-evaluation/LG-05-02.adoc
Fixes #642
Add Scenario-based Analysis as a term,
and replace "Scenario" with "Scenario-based analysis" in list of methods
=> Chapter 5: Add Scenario-based analysis

docs/03-design/LG-03-06.adoc
=> Clarify LG 03-06

documentation/decisions/009-crosscutting-concerns-and-concepts.md
hopefully the ADR-009 on concerns and concepts now works for everybody...
=> 648 lg 03 10 differentiate between cross cutting concerns and cross cutting concepts

docs/02-requirements/LG-02-02.adoc
=> LG 02-02 fix inconsistencies DE-EN

documentation/decisions/010-how-we-decide.md
Thisresult of our voting on our decision-making process
=> #650-META decision on how the FLWG will decide

docs/03-design/LG-03-07.adoc
This a fresh version of the (somewhat broken) PR #639  (where I accidently mixed two changes).
I created this NEW PR so you can better track the changes from OLD to NEW.
=> another try with #564: This time on a fresh branch

docs/01-basics/LG-01-06.adoc
=> LG 01-06 add data, not just data models

docs/02-requirements/LG-02-02.adoc, docs/09-references/00-references.adoc
whow, what a discussion.
@alxlo and myself (plus two different LLMs) spent a long time condensing the discussion and optimizing this compromise.
=> LG-02-02 clarified intro after LENGTHY discussion in #543

documentation/decisions/003-build-curriculum-with-Java.md, documentation/decisions/012-explanation-and-refs-in-glossary.md
@ulibecker or @skogsbaer could you please have a look... thx
=> #577 glossary contains references

README.adoc, docs/09-references/00-references.adoc, documentation/decisions/012-citation_key_standardization.md
- Provide an ADR for consistent citation keys
- Applied to existing bibliography
- Provide short section in README
=> Add and Implement ADR012 for Citation Key Standardization

docs/03-design/01-design-duration-terms.adoc, docs/03-design/LG-03-02.adoc
thanx Roger for pointing out this issue.
=> #686 fixed glossary link to architecture decisions.

docs/03-design/LG-03-02.adoc
=> Fix Minor Typo in Glossary Link

docs/06-examples/LG-06-01.adoc, docs/06-examples/LG-06-02.adoc
minor fix, adding the references to the previous LGs in section 6.
Thanx to https://github.com/mabumann for pointing out this issue.
=> fix #706, added back-references to LG-06-01 and LG-06-02

docs/01-basics/LG-01-07.adoc
I.e. between
- how to structure the data "inside" the software
- where the data is stored, how it is transmitted, queries etc.
See also:
https://github.com/isaqb-org/curriculum-foundation/issues/711
=> Clarify the difference between two aspects of data LG.

docs/04-documentation/LG-04-04.adoc
- Didn't think that this was necessary, but this seems to be the case.
=> Explain the Joke Without Killing The Joke, refs #734 #679 #549

README.adoc
- Reality check of how we have done it, be more precise on revisions.
- Describe the actual conventions we currently use
=> Update Description of Version Tag Conventions in README

build.gradle
- Add support for validity (again)
- Add support for both LG or LZ as descriptors for German learning goals
- Update license to 2025
=> Fix broken curriculum builds

README.adoc
fixed the asciidoc hyperlink syntax (likely it was myself who confused md and adoc again).
=> #752 fixed missing links in readme

docs/04-documentation/LG-04-04.adoc
our first hotfix. The German and English comment on LG 04-04 had been mixed up.
Please, @programming-wolf create the next release version when you have time.
=> #734 LG-04-04 again, exchanged DE and EN comments ("note")

docs/config/setup.adoc
=> Define link to glossary depending on language
