isaqb-org/curriculum-foundation

docs/config/setup.adoc
Applying this PR will remove the "Chapter" part of section headings. 
Example:
```
Chapter 1. Einleitung
```
will become
```
1. Einleitung
```
=> Disable "Chapter" label for section headings

.gitignore, docs/config/i18n-definitions.adoc
The translation for the toc was missing, the definition contained the German text. 🙂 
Closes #83
=> Fix i18n bug with toc

.github/workflows/build_master.yml, README.adoc, build.gradle, docs-ext/EXTERNAL_DOCUMENTS_README.adoc, docs/curriculum-foundation.adoc, docs/index.adoc, gradle/wrapper/gradle-wrapper.properties
With the changes of this branch, we can support the simple upload of translated curricula. They only have to be uploaded to the folder `docs-ext` and will automatically be added to the next release. 
**ATTENTION**:  
The name of the resulting file has been changed from `foundation-curriculum` to `curriculum-foundation` for three reasons:
1. It is now the same format that all advanced modules have as file name (e.g. `curriculum-web`)
2. It allows us to use the same script for advanced modules as well as foundation modules without having to change anything
3. It is now the same name as the repository.
Drawback: with the next release (2021.1), we have to adjust the URL of the Website pointing to this release one more time.
=> Add support for external documents

.github/workflows/build_master.yml, .github/workflows/build_pr.yml, .github/workflows/build_releasecandidate.yml
PDF files of the curriculum are now added to each release and release candidate on github as direct download. Release Candidates are also already published to GitHub Pages.
Sorry for the delay, I thought I had already added that feature.
close #216
=> Add PDF Files to Release

docs/config/i18n-definitions.adoc, docs/curriculum-foundation.adoc
toc-title has to be set directly beneath the very first heading.
Otherwise, it is ignored.
We can remove it from i18n-definitions.adoc
close #236
=> Fix translation of TOC

docs/01-basics/01-basics-duration-terms.adoc, docs/01-basics/LZ-1-02.adoc, docs/01-basics/LZ-1-03.adoc, docs/01-basics/LZ-1-04.adoc, docs/01-basics/LZ-1-07.adoc, docs/02-design/LZ-2-02.adoc, docs/02-design/LZ-2-03.adoc, docs/02-design/LZ-2-06.adoc, docs/03-documentation/LZ-3-01.adoc
... except those in LG 2-8 and Section 4, which are explicitly devoted
to the subject.
This is to help avoid confusion between the use of the term in common
language, and ISO 25010, with the goal of firmly placing the remaining
these uses in the context of ISO 25010.
=> Delete most occurrences of the term "quality"

docs/04-quality/LZ-4-4.adoc
It is intended that the term "Goodhart's Law" is R3 but the effects of the principle should be known as R2.
=> Add mention of Goodhart's Law as R3, refs #255

docs/01-basics/LZ-1-10.adoc
While reviewing the learning goals for changes in the RC, found a typo in the English description of LG-1-10:
_Cloud-native_ Systeme -> _Cloud-native_ systems
This PR fixes the typo.
=> Fix typo in LG-1-10

docs/02-design/LZ-2-05.adoc
Yes, in German it is pipes-and-filter, in Englisch it's pipes-and-filters. Took me a while to get it.
=> Fix small typos in some of the R1 patterns

docs/config/i18n-definitions.adoc
`:chapter_labels:` was defined three times, one definition (in `setup.adoc`) is enough. 
close #343
=> Remove Duplicate Definition

docs/index.adoc
- Remove older versions, only 2021 and 2023 are kept.
- Adjust file to show new 2023 release.
- Remove reference to glossary on LeanPub.
close #366
=> Cleanup overview page

docs/02-design/LZ-2-03.adoc
Rename "product-related factors" to "product-related requirements, as in the german version
Remove topics from the "product-related requirements" section that have a dedicated section
Fixes #372
=> LG 2-3: Remove redundancies and inconsistencies

docs/02-design/LZ-2-05.adoc
Fixes #380.
I've generally follow @ulibecker's suggestion, but avoided the word "consumer" which is used differently elsewhere in the curriculum.
=> Improve description of observer pattern.

docs/02-design/99-design-references.adoc, docs/02-design/LZ-2-05.adoc, docs/09-references/00-references.adoc
Gregor Hohpe's book Enterprise Integration Patterns was missing from our list of references, but was referenced via plain text in one of the learning goals.
Close #385
=> Add Missing Reference

docs/03-design/LZ-03-08.adoc
The term "solution pattern" is not defined in the curriculum, and only appears in this one place.
Fixes #427.
=> Remove the "solution" from "solution pattern".

docs/05-evaluation/LZ-05-02.adoc
=> Improve listing of specific metrics

docs/09-references/00-references.adoc
- ISO25010:2023 has been released
- added ISO25019:2023 because parts of the old norm ended up there and quality-in-use is relevant as well
=> Replace reference for ISO25010 draft with released 25010+25019

README.adoc
Just found out that building the documents didn't work anymore. Updating to Java 21 fixed that for me.
=> Update Java info in README.adoc

CHANGELOG.md, documentation/changelogs/readme-changelogs.md
added content to CHANGELOG.md. Should be good enough (together with graphical overview) to allow smooth migration from V2023 to V2025.
=> #443 migration guide

docs/config/setup.adoc
We decided years ago that we do not want to use `Chapter 1 This is Chapter One / Kapitel 1 Dies ist Kapitel eins` but want to name the chapters as follows:
`1 This is Chapter One / 1 Dies ist Kapitel eins`
By using the proper configuration key, we achieve this. 🙂 
close #536
=> Fix Chapter Names

docs/01-basics/01-basics-duration-terms.adoc, docs/01-basics/LZ-01-01.adoc, docs/02-requirements/LZ-02-04.adoc, docs/config/setup.adoc
- Demonstrate how every (!) learning goal has to define its own references section
- Fix configuration to also include text that is not enclosed in language tags
- Remove bibref variable to trigger warnings: Once every learning goal of a chapter has its own references section, the references file causing the warning has to be removed. 
- Fix broken reference to glossary
- Fix broken learning goal reference
See #535
=> Create Section for References

docs/03-design/LG-03-04.adoc
added DRY (again), and fixed a few relevance-levels
=> #578-add-DRY-to-LG-03-04

docs/04-documentation/LG-04-07.adoc
Fixes #640
Map cross-cutting concern to aspect and solution concept for a cross-cutting
concern to a cross-cutting concept
=> Clarify cross-cutting concerns vs. cross-cutting concepts

README.adoc, documentation/decisions/012-citation_key_standardization.md
I propose to modify the (awesome!) ADR-012 from @alxlo in one tiny aspect:
References with multiple authors previously read `[Bass+ 2021]` containing a blank between the + and the year.
The proposal is to remove the blank, resulting in `[Bass+2021]'.
Reason: I consider this to be more aesthetically pleasing.
=> #675, propose to simplify citation key for multiple authors (remove blank)

docs/05-evaluation/LG-05-02.adoc
@michaelpog please also have a look.
I changed the rating in the LG title from (R1,R3) to "R1-R3" and removed one R2 in the EN version
(seems the DE version was more consistent)
=> #692,proposed fixes for ratings

docs/09-references/00-references.adoc
Update to second edition
Change from Ford to Ford+ since the book has several authors
Fixes #709
=> Update reference to Evolutionary Architecture Book to 2nd edition

CHANGELOG.md
They were re-introduced in #594.
=> Undelete SOLID principles from CHANGELOG

docs/02-requirements/LG-02-01.adoc
... as there are no more R2 parts inside, and for the sake of consistency with the other LGs
=> Indicate (R1, R3) instead (R1-R3) for LG 02-01

docs/03-design/LG-03-07.adoc
- move "service" to heading
- re-label "service-oriented" as "procedure-oriented"
- move GraphQL to "procedure-oriented"
=> Clarify sub-goal on remote service interfaces.

docs/01-basics/LG-01-05.adoc, docs/02-requirements/LG-02-04.adoc, docs/02-requirements/LG-02-05.adoc, docs/03-design/LG-03-02.adoc, docs/03-design/LG-03-03.adoc, docs/03-design/LG-03-04.adoc, docs/03-design/LG-03-05.adoc, docs/03-design/LG-03-06.adoc, docs/03-design/LG-03-07.adoc, docs/03-design/LG-03-08.adoc, docs/03-design/LG-03-09.adoc, docs/03-design/LG-03-10.adoc, docs/04-documentation/LG-04-01.adoc, docs/04-documentation/LG-04-02.adoc, docs/04-documentation/LG-04-03.adoc, docs/04-documentation/LG-04-05.adoc, docs/04-documentation/LG-04-06.adoc, docs/04-documentation/LG-04-08.adoc, docs/04-documentation/LG-04-09.adoc, docs/06-examples/LG-06-01.adoc, docs/06-examples/LG-06-02.adoc
- numbers in old LGs had no leading zeros
- in some places this was correct (previously LG x-y), in some places we had x-0y, in some places even 0x-0y
- call me a bean counter
=> Handle References to Old LGs Consistently

docs/02-requirements/LG-02-02.adoc
next hotfix: In LG-02-02 we (wrongly) referenced "Head-First Architecture" instead of [Gharbi+24].
This PR fixes that.
=> LG-02-02, fixed reference Gharbi+24

docs/03-design/LG-03-08.adoc
Glossary links in LG 03-08 are not working: https://public.isaqb.org/curriculum-foundation/curriculum-foundation-en.html
=> Fix LG 03-08 term links
